### ISSUE TITLE
Do not use hyphen in bug ID

### ISSUE THREAD

**Issue by seongjoonh** [kupl/starlab-benchmarks#43]
snort-2.9.13?
recutils-1.8?
scikit-learn?

**Comment by henrylee97** [comment]
What is the problem?
Please give more informations

**Comment by seongjoonh** [comment]
snort-2.9.13-1의 인덱스는 뭐죠그럼

**Comment by henrylee97** [comment]
SAVER_public_1 == {public, 1} ?

**Comment by henrylee97** [comment]
@seongjoonh Thank you for your interest in our repository, but we decided to use the indices of bugs as the last word from the sequence split by `hyphen (-)`.

If you need further discussion, please re-open this issue :)
